# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: abhilasha
# "service" is the name of this project. This will also be added to your AWS resource names.
service: project-serverless

provider:
  name: aws
  runtime: nodejs20.x
  region: ap-south-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:GetObject
        - s3:PutObject
        - s3:ListBucket
        - s3:DeleteObject
      Resource: "*"

package:
    exclude:
    - node_modules/** 

plugins:
  - serverless-offline
 

functions:

  register:
    handler: handler.registerHandler
    events:
      - http:
          path: register
          method: post

  confirm:
    handler: handler.confirmHandler
    events:
      - http:
          path: confirm
          method: post

  login:
    handler: handler.login1Handler
    events:
      - http:
          path: login
          method: post

  # createTopic:
  #   handler: handler.createTopicHandler
  #   events:
  #     - http:
  #         path: createTopic
  #         method: post
 
  # subscribeToTopic:
  #   handler: handler.subscribeToTopicHandler
  #   events:
  #     - http:
  #         path: subscribeToTopic
  #         method: post

  publishMessage:
    handler: handler.publishMessageHandler
    timeout: 30

    events:
      - http:
          path: publish
          method: post
  
  # createQueue:
  #   handler: handler.createQueueHandler
  #   events:
  #     - http:
  #         path: createQueue
  #         method: post

  sendMessageToQueue:
    handler: handler.sendMessageToQueueHandler
    events:
      - http:
          path: sendMessageQueue
          method: post

  receiveMessageToQueue:
    handler: handler.receiveMessageToQueueHandler
    events:
      - http:
          path: receiveMessage
          method: get

  sendEmailToQueue:
    handler: handler.sendEmailToHandler
    events:
      - http:
          path: sendEmailToQueue
          method: post

  uploadObject:
    handler: handler.uploadObjectHandler
    events:
      - http:
          path: uploadObject
          method: post

  getObject:
    handler: handler.getObjectHandler
    events:
      - http:
          path: getObject
          method: post

  listObjects:
    handler: handler.listObjectsHandler
    events:
      - http:
          path: listObjects
          method: post

  deleteObject:
    handler: handler.deleteObjectHandler
    events:
      - http:
          path: deleteObject
          method: post